"""

CREATE STREAM raw_checkin_stream
  WITH (
    KAFKA_TOPIC='topic_.Bigdata23.checkin', -- Specify the existing Kafka topic here
    VALUE_FORMAT='AVRO'
  );

 CREATE STREAM processed_checkin_stream WITH
 (TIMESTAMP='CHECKIN_TIME', TIMESTAMP_FORMAT='yyyy-MM-dd HH:mm:ss') AS SELECT
  RAW_CHECKIN_STREAM.FULLDOCUMENT->RESTAURANT_ID RESTAURANT_ID,
  RAW_CHECKIN_STREAM.FULLDOCUMENT->PARTY_SIZE PARTY_SIZE,
  RAW_CHECKIN_STREAM.FULLDOCUMENT->USER_ID USER_ID,
  RAW_CHECKIN_STREAM.FULLDOCUMENT->CHECKIN_TIME CHECKIN_TIME
FROM RAW_CHECKIN_STREAM RAW_CHECKIN_STREAM
EMIT CHANGES;

CREATE TABLE AGG_Checkins AS SELECT
  PROCESSED_CHECKIN_STREAM.RESTAURANT_ID RESTAURANT_ID,
  SUM(PROCESSED_CHECKIN_STREAM.PARTY_SIZE) TOTAL_PARTY_SIZE
FROM PROCESSED_CHECKIN_STREAM PROCESSED_CHECKIN_STREAM
WINDOW TUMBLING ( SIZE 2 HOURS )
GROUP BY PROCESSED_CHECKIN_STREAM.RESTAURANT_ID
EMIT CHANGES;

"""